<?php

	if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5f0db0eb77845',
		'title' => 'Block: Container Settings',
		'fields' => array(
			array(
				'key' => 'field_5f0db0ffe6d04',
				'label' => 'Container Styles',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5f0db11ce6d05',
				'label' => 'Background Color',
				'name' => 'wrapper_background',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5f0db140e6d06',
				'label' => 'Background Image',
				'name' => 'wrapper_background_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5ee8ee597jhg',
				'label' => 'Container Layout',
				'name' => 'container_layout',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Content Width',
					'page-width' => 'Page Width'
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5f0db21be6d08',
				'label' => 'Spacing',
				'name' => 'spacing',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => 200,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5f0db157e6d07',
				'label' => 'Shape Divider',
				'name' => 'shape_divider',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'slant' => 'Slant',
					'slant-up' => 'Slant Indent',
					'sharp-slant' => 'Geometric Slants',
					'faded-slant' => 'Faded Slant',
					'wave-loop' => 'Wave Loop',
					'basic-triangle' => 'Basic Triangle',
					'side-triangle' => 'Side Triangle',
					'round' => 'Rounded',
					'clouds' => 'Clouds',
					'faded-clouds' => 'Faded Clouds',
					'shred-paper' => 'Shredded Paper',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'all',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	endif;
?>