<?php
	
	if( function_exists('acf_add_local_field_group') ):

	// General Options
	acf_add_local_field_group(array(
		'key' => 'group_5ef0b2c989733',
		'title' => 'Options: Theme Settings',
		'fields' => array(
			array(
				'key' => 'field_5ef0d884f4cb6',
				'label' => 'Basic Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef0cdc43f8fd',
				'label' => 'Favicon',
				'name' => 'favicon',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5ef35b6639823kj',
				'label' => 'Content Width',
				'name' => 'content_width',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => 1200,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5ef0b47107723',
				'label' => 'Theme Colors',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef0b59107724',
				'label' => 'Primary Color',
				'name' => 'primary_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef0b5a007725',
				'label' => 'Secondary Color',
				'name' => 'secondary_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef0b5bc07726',
				'label' => 'Accent Color 1',
				'name' => 'accent_color_one',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef0b5cf07727',
				'label' => 'Accent Color 2',
				'name' => 'accent_color_two',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef0b5f107728',
				'label' => 'Typography',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef2448f2w234ds',
				'label' => 'Main Copy',
				'name' => 'body_copy',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 16,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef2448fcbf6d',
				'label' => 'Header 1',
				'name' => 'header_1',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 60,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef24423sdf',
				'label' => 'Header 2',
				'name' => 'header_2',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 48,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef24456dfgdf',
				'label' => 'Header 3',
				'name' => 'header_3',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 36,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef24567rghegs',
				'label' => 'Header 4',
				'name' => 'header_4',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 28,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef2456234sdf',
				'label' => 'Header 5',
				'name' => 'header_5',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 21,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef24562234sdfgf',
				'label' => 'Header 6',
				'name' => 'header_6',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 16,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			
			array(
				'key' => 'field_5ef0c4813f8ef',
				'label' => 'Link',
				'name' => 'link_type',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 16,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef0c4ba3f8f0',
				'label' => 'Link Hover',
				'name' => 'link_hover',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					1 => 'font_style',
					2 => 'text_color',
					3 => 'text_decoration',
				),
				'required_properties' => '',
				'font_size' => 15,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef0ce123f8fe',
				'label' => 'Forms',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef34e0ea12fe',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<h3>Basic Form Styles</h3>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ef0cf9a3f900',
				'label' => 'Border Color',
				'name' => 'border_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef0cfa53f901',
				'label' => 'Border Width',
				'name' => 'border_width',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => 10,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5ef0cfb93f902',
				'label' => 'Background Color',
				'name' => 'background_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef0cfc73f903',
				'label' => 'Form Typography',
				'name' => 'form_typography',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'line_height',
					4 => 'text_color',
					5 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 15,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef0d35d3f908',
				'label' => 'Margin',
				'name' => 'margin',
				'type' => 'range',
				'instructions' => 'Margin above form fields',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => 200,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5ef34e2397sk',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<h3>Textarea</h3>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ef0d1d33f905',
				'label' => 'Input Hight',
				'name' => 'input_hight',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => 300,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5ef34e0e37s9s',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<h3>Select Fields</h3>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ef0d2853f907',
				'label' => 'Arrow Color',
				'name' => 'arrow_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef0c58a3f8f1',
				'label' => 'Buttons',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef34e0e98sj',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<h3>Primary Button</h3>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ef25f1bc5d87',
				'label' => 'Primary Typography',
				'name' => 'primary_button_typography',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 16,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef25f68c5d88',
				'label' => 'Primary Background',
				'name' => 'primary_button_background',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef25fe4c5d8a',
				'label' => 'Primary Border Width',
				'name' => 'primary_border_width',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => 10,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5ef25f9fc5d89',
				'label' => 'Primary Border Color',
				'name' => 'primary_border_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef34e02983ls',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<h3>Secondary Button</h3>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ef26032c5d8b',
				'label' => 'Secondary Typography',
				'name' => 'secondary_typography',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 16,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef26064c5d8c',
				'label' => 'Secondary Background',
				'name' => 'secondary_background',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef26080c5d8d',
				'label' => 'Secondary Border Width',
				'name' => 'secondary_border_width',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => 10,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5ef2609ac5d8e',
				'label' => 'Secondary Border Color',
				'name' => 'secondary_border_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-general-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	//Header Options
	acf_add_local_field_group(array(
		'key' => 'group_5ef359fd797ae',
		'title' => 'Options: Header',
		'fields' => array(
			array(
				'key' => 'field_5ef35a48363ea',
				'label' => 'Header Layout',
				'name' => 'header_layout',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'basic-layout' => 'Basic Navigation',
					'full-screen' => 'Full Screen Navigation',
					'stripped' => 'Stripped Navigation',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ef36628363f9',
				'label' => 'Header Height',
				'name' => 'header_height',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => 400,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5ef35afe363eb',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<h3>Site Branding</h3>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ef35cdc323o8s',
				'label' => 'Header Background Color',
				'name' => 'header_background',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef35b39363ec',
				'label' => 'Logo',
				'name' => 'logo',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5ef35b55363ed',
				'label' => 'Logo Width',
				'name' => 'logo_width',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => 400,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5ef35b66363ee',
				'label' => 'Logo Max-Width',
				'name' => 'logo_max-width',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => 400,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5ef35ba2363ef',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<h3>Header Typography</h3>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ef35bbb363f0',
				'label' => 'Menu Items',
				'name' => 'menu_items',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'line_height',
					4 => 'letter_spacing',
					5 => 'text_color',
					6 => 'text_decoration',
					7 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 16,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef35c46363f1',
				'label' => 'Search Bar',
				'name' => 'search_bar',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_color',
					7 => 'text_decoration',
					8 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 16,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef35cb3363f2',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ef35a48363ea',
							'operator' => '==',
							'value' => 'full-screen',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<h3>Full Width</h3>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5ef35cdc363f3',
				'label' => 'Open Icon Color',
				'name' => 'open_icon_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef3650c363f4',
				'label' => 'Close Icon Color',
				'name' => 'close_icon_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5ef36551363f5',
				'label' => 'Full Screen Background Color',
				'name' => 'full_screen_background_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-header',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	endif;

?>