<?php

	if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5ef0b2c989733',
	'title' => 'Options: Theme Settings',
	'fields' => array(
		array(
			'key' => 'field_5ef0d884f4cb6',
			'label' => 'Logo',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ef0b44a07722',
			'label' => 'Company Logo',
			'name' => 'company_logo',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5ef0d7ed54f9c',
					'label' => 'Logo',
					'name' => 'logo',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5ef0d7fb54f9d',
					'label' => 'Width',
					'name' => 'width',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => 500,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5ef0d80f54f9e',
					'label' => 'Max-Width',
					'name' => 'max-width',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => 500,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_5ef0cdc43f8fd',
			'label' => 'Favicon',
			'name' => 'favicon',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5ef0b47107723',
			'label' => 'Theme Colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ef0b59107724',
			'label' => 'Primary Color',
			'name' => 'primary_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5ef0b5a007725',
			'label' => 'Secondary Color',
			'name' => 'secondary_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5ef0b5bc07726',
			'label' => 'Accent Color 1',
			'name' => 'accent_color_one',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5ef0b5cf07727',
			'label' => 'Accent Color 2',
			'name' => 'accent_color_two',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5ef0b5f107728',
			'label' => 'Typography',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
		'key' => 'field_5ef3b72c5133a',
		'label' => 'Typography Settings',
		'name' => 'typo_test',
		'type' => 'group',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'layout' => 'block',
		'sub_fields' => array(
			array(
				'key' => 'field_main_content_tab',
				'label' => 'Body',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef2448f2w234ds',
				'label' => 'Body Copy',
				'name' => 'body_copy',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 16,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_h1_tab',
				'label' => 'H1',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef2448fcbf6d',
				'label' => 'Header 1',
				'name' => 'header_1',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 60,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_h2_tab',
				'label' => 'H2',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef24423sdf',
				'label' => 'Header 2',
				'name' => 'header_2',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 48,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_h3_tab',
				'label' => 'H3',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef24456dfgdf',
				'label' => 'Header 3',
				'name' => 'header_3',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 36,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_h4_tab',
				'label' => 'H4',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef24567rghegs',
				'label' => 'Header 4',
				'name' => 'header_4',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 28,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_h5_tab',
				'label' => 'H5',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef2456234sdf',
				'label' => 'Header 5',
				'name' => 'header_5',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 21,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_h6_tab',
				'label' => 'H6',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef24562234sdfgf',
				'label' => 'Header 6',
				'name' => 'header_6',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
					2 => 'font_weight',
					3 => 'font_style',
					4 => 'line_height',
					5 => 'letter_spacing',
					6 => 'text_align',
					7 => 'text_color',
					8 => 'text_decoration',
					9 => 'text_transform',
				),
				'required_properties' => '',
				'font_size' => 16,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '1.2',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_links_tab',
				'label' => 'Links',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ef0c4813f8ef',
				'label' => 'Link',
				'name' => 'link_type',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_size',
					1 => 'font_family',
				),
				'required_properties' => '',
				'font_size' => 15,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			array(
				'key' => 'field_5ef0c4ba3f8f0',
				'label' => 'Link Hover',
				'name' => 'link_hover',
				'type' => 'Typography',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_properties' => array(
					0 => 'font_weight',
					1 => 'font_style',
					2 => 'text_color',
					3 => 'text_decoration',
				),
				'required_properties' => '',
				'font_size' => 15,
				'font_family' => 'Arial, Helvetica, sans-serif',
				'font_weight' => 400,
				'font_style' => 'normal',
				'font_variant' => 'normal',
				'font_stretch' => 'normal',
				'line_height' => '',
				'letter_spacing' => 0,
				'text_align' => 'left',
				'text_color' => '#000',
				'text_decoration' => 'none',
				'text_transform' => 'none',
			),
			),
		),
		array(
			'key' => 'field_5ef0c58a3f8f1',
			'label' => 'Buttons',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ef0c5963f8f2',
			'label' => 'Primary Button',
			'name' => 'primary_button',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5ef0c5c93f8f3',
					'label' => 'Button Typography',
					'name' => 'prime_button_typography',
					'type' => 'Typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_properties' => array(
						0 => 'font_size',
						1 => 'font_family',
						2 => 'font_weight',
						3 => 'font_style',
						4 => 'font_variant',
						5 => 'font_stretch',
						6 => 'line_height',
						7 => 'letter_spacing',
						8 => 'text_align',
						9 => 'text_color',
						10 => 'text_decoration',
						11 => 'text_transform',
					),
					'required_properties' => '',
					'font_size' => 15,
					'font_family' => 'Arial, Helvetica, sans-serif',
					'font_weight' => 400,
					'font_style' => 'normal',
					'font_variant' => 'normal',
					'font_stretch' => 'normal',
					'line_height' => '',
					'letter_spacing' => 0,
					'text_align' => 'left',
					'text_color' => '#000',
					'text_decoration' => 'none',
					'text_transform' => 'none',
				),
				array(
					'key' => 'field_5ef0c5f13f8f4',
					'label' => 'Button Background',
					'name' => 'prime_button_background',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5ef0c6183f8f5',
					'label' => 'Button Border Color',
					'name' => 'prime_button_border_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5ef0c63d3f8f6',
					'label' => 'Button Border Width',
					'name' => 'button_border_width',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => 10,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_5ef0cc813f8f8',
			'label' => 'Secondary Button',
			'name' => 'secondary_button',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5ef0cc813f8f9',
					'label' => 'Button Typography',
					'name' => 'sec_button_typography',
					'type' => 'Typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_properties' => array(
						0 => 'font_size',
						1 => 'font_family',
						2 => 'font_weight',
						3 => 'font_style',
						4 => 'font_variant',
						5 => 'font_stretch',
						6 => 'line_height',
						7 => 'letter_spacing',
						8 => 'text_align',
						9 => 'text_color',
						10 => 'text_decoration',
						11 => 'text_transform',
					),
					'required_properties' => '',
					'font_size' => 15,
					'font_family' => 'Arial, Helvetica, sans-serif',
					'font_weight' => 400,
					'font_style' => 'normal',
					'font_variant' => 'normal',
					'font_stretch' => 'normal',
					'line_height' => '',
					'letter_spacing' => 0,
					'text_align' => 'left',
					'text_color' => '#000',
					'text_decoration' => 'none',
					'text_transform' => 'none',
				),
				array(
					'key' => 'field_5ef0cc813f8fa',
					'label' => 'Button Background',
					'name' => 'sec_button_background',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5ef0cc813f8fb',
					'label' => 'Button Border Color',
					'name' => 'sec_button_border_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5ef0cc813f8fc',
					'label' => 'Button Border Width',
					'name' => 'sec_border_width',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => 10,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_5ef0ce123f8fe',
			'label' => 'Forms',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ef0ce203f8ff',
			'label' => 'General',
			'name' => 'general_form',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5ef0cf9a3f900',
					'label' => 'Border Color',
					'name' => 'border_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5ef0cfa53f901',
					'label' => 'Border Width',
					'name' => 'border_width',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => 10,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5ef0cfb93f902',
					'label' => 'Background Color',
					'name' => 'background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5ef0cfc73f903',
					'label' => 'Form Typography',
					'name' => 'form_typography',
					'type' => 'Typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_properties' => array(
						0 => 'font_size',
						1 => 'font_family',
						2 => 'font_weight',
						3 => 'line_height',
						4 => 'text_color',
						5 => 'text_transform',
					),
					'required_properties' => '',
					'font_size' => 15,
					'font_family' => 'Arial, Helvetica, sans-serif',
					'font_weight' => 400,
					'font_style' => 'normal',
					'font_variant' => 'normal',
					'font_stretch' => 'normal',
					'line_height' => '',
					'letter_spacing' => 0,
					'text_align' => 'left',
					'text_color' => '#000',
					'text_decoration' => 'none',
					'text_transform' => 'none',
				),
				array(
					'key' => 'field_5ef0d35d3f908',
					'label' => 'Margin',
					'name' => 'margin',
					'type' => 'range',
					'instructions' => 'Margin above form fields',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => 200,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_5ef0cfea3f904',
			'label' => 'Textarea',
			'name' => 'textarea',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5ef0d1d33f905',
					'label' => 'Input Hight',
					'name' => 'input_hight',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => 300,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_5ef0d2773f906',
			'label' => 'Select',
			'name' => 'select',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5ef0d2853f907',
					'label' => 'Arrow Color',
					'name' => 'arrow_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;

?>
